[package]
name = "monkeypdf"
version = "0.1.0"
description = "MonkeyPDF - Desktop PDF toolkit"
authors = ["MonkeyPDF"]
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
log = "0.4"
tauri = { version = "2", features = [] }
tauri-plugin-log = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
thiserror = "2"
lopdf = "0.34"
pdfium-render = "0.8"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp"] }
base64 = "0.22"
tauri-plugin-notification = "2.3.3"
notify-rust = "4"
